CELLS_ROW_SIZE = 7
CELLS_COLUMN_SIZE =5
WINDOW_HEIGHT = 500
WINDOW_WIDTH = 500

CELLS_ROW_SIZE = 16
CELLS_COLUMN_SIZE = 16
WINDOW_HEIGHT = 1000
WINDOW_WIDTH = 1000


ROWS_PADDING = WINDOW_HEIGHT // CELLS_ROW_SIZE
COLS_PADDING = WINDOW_WIDTH // CELLS_COLUMN_SIZE

